package com.eclipse.sniffer.tables;

import com.eclipse.sniffer.enums.EnchantList;

import java.util.HashMap;
import java.util.Map;

// Reference: https://github.com/OpenKore/openkore/blob/master/tables/iRO/Transcendence/item_options.txt
public class ItemEnchantProperty {

    private static final Map<EnchantList, String> enchants;
    static {
        Map<EnchantList, String> enc = new HashMap<>();
        enc.put(EnchantList.UNKNOWN, "Unknown %d");
        enc.put(EnchantList.VAR_MAXHPAMOUNT, "Max HP + %d");
        enc.put(EnchantList.VAR_MAXSPAMOUNT, "Max SP + %d");
        enc.put(EnchantList.VAR_STRAMOUNT, "Str + %d");
        enc.put(EnchantList.VAR_AGIAMOUNT, "Agi + %d");
        enc.put(EnchantList.VAR_VITAMOUNT, "Vit + %d");
        enc.put(EnchantList.VAR_INTAMOUNT, "Int + %d");
        enc.put(EnchantList.VAR_DEXAMOUNT, "Dex + %d");
        enc.put(EnchantList.VAR_LUKAMOUNT, "Luk + %d");
        enc.put(EnchantList.VAR_MAXHPPERCENT, "Max HP + %d%%");
        enc.put(EnchantList.VAR_MAXSPPERCENT, "Max SP + %d%%");
        enc.put(EnchantList.VAR_HPACCELERATION, "HP Recovery + %d%%");
        enc.put(EnchantList.VAR_SPACCELERATION, "SP Recovery + %d%%");
        enc.put(EnchantList.VAR_ATKPERCENT, "Atk + %d%%");
        enc.put(EnchantList.VAR_MAGICATKPERCENT, "Matk + %d%%");
        enc.put(EnchantList.VAR_PLUSASPD, "Aspd + %d");
        enc.put(EnchantList.VAR_PLUSASPDPERCENT, "Aspd + %d%%");
        enc.put(EnchantList.VAR_ATTPOWER, "Atk + %d");
        enc.put(EnchantList.VAR_HITSUCCESSVALUE, "Hit + %d");
        enc.put(EnchantList.VAR_ATTMPOWER, "Matk + %d");
        enc.put(EnchantList.VAR_ITEMDEFPOWER, "Def + %d");
        enc.put(EnchantList.VAR_MDEFPOWER, "Mdef + %d");
        enc.put(EnchantList.VAR_AVOIDSUCCESSVALUE, "Flee + %d");
        enc.put(EnchantList.VAR_PLUSAVOIDSUCCESSVALUE, "Perfect Dodge + %d");
        enc.put(EnchantList.VAR_CRITICALSUCCESSVALUE, "Crit + %d");
        enc.put(EnchantList.ATTR_TOLERACE_NOTHING, "Neutral Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_WATER, "Water Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_GROUND, "Earth Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_FIRE, "Fire Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_WIND, "Wind Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_POISON, "Poison Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_SAINT, "Holy Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_DARKNESS, "Shadow Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_TELEKINESIS, "Ghost Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_UNDEAD, "Undead Property Resistance +%d%%.");
        enc.put(EnchantList.ATTR_TOLERACE_ALL, "All Property Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_NOTHING_USER, "Neutral Enemies Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_NOTHING_TARGET, "Damage to Neutral Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_WATER_USER, "Water Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_WATER_TARGET, "Damage to Water Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_GROUND_USER, "Earth Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_GROUND_TARGET, "Damage to Earth Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_FIRE_USER, "Fire Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_FIRE_TARGET, "Damage to Fire Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_WIND_USER, "Wind Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_WIND_TARGET, "Damage to Wind Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_POISON_USER, "Poison Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_POISON_TARGET, "Damage to Poison Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_SAINT_USER, "Holy Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_SAINT_TARGET, "Damage to Holy Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_DARKNESS_USER, "Shadow Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_DARKNESS_TARGET, "Damage to Shadow Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_TELEKINESIS_USER, "Ghost Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_TELEKINESIS_TARGET, "Damage to Ghost Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_UNDEAD_USER, "Undead Property Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_PROPERTY_UNDEAD_TARGET, "Damage to Undead Property Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_NOTHING_USER, "Neutral Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_NOTHING_TARGET, "Magic Damage to Neutral Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_WATER_USER, "Water Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_WATER_TARGET, "Magic Damage to Water Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_GROUND_USER, "Earth Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_GROUND_TARGET, "Magic Damage to Earth Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_FIRE_USER, "Fire Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_FIRE_TARGET, "Magic Damage to Fire Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_WIND_USER, "Wind Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_WIND_TARGET, "Magic Damage to Wind Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_POISON_USER, "Poison Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_POISON_TARGET, "Magic Damage to Poison Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_SAINT_USER, "Holy Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_SAINT_TARGET, "Magic Damage to Holy Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_DARKNESS_USER, "Shadow Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_DARKNESS_TARGET, "Magic Damage to Shadow Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_TELEKINESIS_USER, "Ghost Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_TELEKINESIS_TARGET, "Magic Damage to Ghost Enemies +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_UNDEAD_USER, "Undead Property Enemy Magic Resistance +%d%%.");
        enc.put(EnchantList.MDAMAGE_PROPERTY_UNDEAD_TARGET, "Undead Property Enemy +%d%%.");
        enc.put(EnchantList.BODY_ATTR_WATER, "User's Property Water.");
        enc.put(EnchantList.BODY_ATTR_GROUND, "User's Property Earth.");
        enc.put(EnchantList.BODY_ATTR_FIRE, "User's Property Fire.");
        enc.put(EnchantList.BODY_ATTR_WIND, "User's Property Wind.");
        enc.put(EnchantList.BODY_ATTR_POISON, "User's Property Poison.");
        enc.put(EnchantList.BODY_ATTR_SAINT, "User's Property Holy.");
        enc.put(EnchantList.BODY_ATTR_DARKNESS, "User's Property Shadow.");
        enc.put(EnchantList.BODY_ATTR_TELEKINESIS, "User's Property Ghost.");
        enc.put(EnchantList.BODY_ATTR_UNDEAD, "User's Property Undead.");
        enc.put(EnchantList.RACE_TOLERACE_NOTHING, "Formless Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_UNDEAD, "Undead Race Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_ANIMAL, "Brute Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_PLANT, "Plant Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_INSECT, "Insect Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_FISHS, "Fish Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_DEVIL, "Demon Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_HUMAN, "Demi-Human Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_ANGEL, "Angel Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_TOLERACE_DRAGON, "Dragon Enemy Resistance +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_NOTHING, "Damage to Formless Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_UNDEAD, "Damage to Undead Race Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_ANIMAL, "Damage to Brute Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_PLANT, "Damage to Plant Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_INSECT, "Damage to Insect Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_FISHS, "Damage to Fish Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_DEVIL, "Damage to Demon Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_HUMAN, "Damage to Demi-Human Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_ANGEL, "Damage to Angel Enemies +%d%%.");
        enc.put(EnchantList.RACE_DAMAGE_DRAGON, "Damage to Dragon Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_NOTHING, "Magic Damage to Formless Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_UNDEAD, "Magic Damage to Undead Race Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_ANIMAL, "Magic Damage to Brute Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_PLANT, "Magic Damage to Plant Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_INSECT, "Magic Damage to Insect Enemy +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_FISHS, "Magic Damage to Fish Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_DEVIL, "Magic Damage to Demon Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_HUMAN, "Magic Damage to Demi-Human Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_ANGEL, "Magic Damage to Angel Enemies +%d%%.");
        enc.put(EnchantList.RACE_MDAMAGE_DRAGON, "Magic Damage to Dragon Enemies +%d%%.");
        enc.put(EnchantList.RACE_CRI_PERCENT_NOTHING, "Crit + (%d / 10) on Formless Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_UNDEAD, "Crit + (%d / 10) on Undead Race Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_ANIMAL, "Crit + (%d / 10) on Brute Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_PLANT, "Crit + (%d / 10) on Plant Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_INSECT, "Crit + (%d / 10) on Insect Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_FISHS, "Crit + (%d / 10) on Fish Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_DEVIL, "Crit + (%d / 10) on Demon Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_HUMAN, "Crit + (%d / 10) on Demi-Human Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_ANGEL, "Crit + (%d / 10) on Angel Enemies.");
        enc.put(EnchantList.RACE_CRI_PERCENT_DRAGON, "Crit + (%d / 10) on Dragon Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_NOTHING, "Bypass %d%% of Def on Formless Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_UNDEAD, "Bypass %d%% of Def on Undead Race Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_ANIMAL, "Bypass %d%% of Def on Brute Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_PLANT, "Bypass %d%% of Def on Plant Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_INSECT, "Bypass %d%% of Def on Insect Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_FISHS, "Bypass %d%% of Def on Fish Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_DEVIL, "Bypass %d%% of Def on Demon Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_HUMAN, "Bypass %d%% of Def on Demi-Human Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_ANGEL, "Bypass %d%% of Def on Angel Enemies.");
        enc.put(EnchantList.RACE_IGNORE_DEF_PERCENT_DRAGON, "Bypass %d%% of Def on Dragon Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_NOTHING, "Bypass %d%% of Mdef on Formless Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_UNDEAD, "Bypass %d%% of Mdef on Undead Race Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_ANIMAL, "Bypass %d%% of Mdef on Brute Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_PLANT, "Bypass %d%% of Mdef on Plant Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_INSECT, "Bypass %d%% of Mdef on Insect Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_FISHS, "Bypass %d%% of Mdef on Fish Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_DEVIL, "Bypass %d%% of Mdef on Demon Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_HUMAN, "Bypass %d%% of Mdef on Demi-Human Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_ANGEL, "Bypass %d%% of Mdef on Angel Enemies.");
        enc.put(EnchantList.RACE_IGNORE_MDEF_PERCENT_DRAGON, "Bypass %d%% of Mdef on Dragon Enemies.");
        enc.put(EnchantList.CLASS_DAMAGE_NORMAL_TARGET, "Damage to Normal Enemies +%d%%.");
        enc.put(EnchantList.CLASS_DAMAGE_BOSS_TARGET, "Damage to Damage to Boss Enemies +%d%%.");
        enc.put(EnchantList.CLASS_DAMAGE_NORMAL_USER, "Normal Enemy Resistance +%d%%.");
        enc.put(EnchantList.CLASS_DAMAGE_BOSS_USER, "Boss Enemy Resistance +%d%%.");
        enc.put(EnchantList.CLASS_MDAMAGE_NORMAL, "Magic Damage to Normal Enemies +%d%%.");
        enc.put(EnchantList.CLASS_MDAMAGE_BOSS, "Magic Damage to Boss Enemies +%d%%.");
        enc.put(EnchantList.CLASS_IGNORE_DEF_PERCENT_NORMAL, "Bypass %d%% of Def on Normal Enemies.");
        enc.put(EnchantList.CLASS_IGNORE_DEF_PERCENT_BOSS, "Bypass %d%% of Def on Boss Enemies.");
        enc.put(EnchantList.CLASS_IGNORE_MDEF_PERCENT_NORMAL, "Bypass %d%% of Mdef on Normal Enemies.");
        enc.put(EnchantList.CLASS_IGNORE_MDEF_PERCENT_BOSS, "Bypass %d%% of Mdef on Boss Enemies.");
        enc.put(EnchantList.DAMAGE_SIZE_SMALL_TARGET, "Damage to Small Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_SIZE_MIDIUM_TARGET, "Damage to Medium Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_SIZE_LARGE_TARGET, "Damage to Large Enemies +%d%%.");
        enc.put(EnchantList.DAMAGE_SIZE_SMALL_USER, "Small Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_SIZE_MIDIUM_USER, "Medium Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_SIZE_LARGE_USER, "Large Enemy Resistance +%d%%.");
        enc.put(EnchantList.DAMAGE_SIZE_PERFECT, "Recovers 100% of damage lost from size penalties.");
        enc.put(EnchantList.DAMAGE_CRI_TARGET, "Critical Damage +%d%%.");
        enc.put(EnchantList.DAMAGE_CRI_USER, "Critical Resistance +%d%%.");
        enc.put(EnchantList.RANGE_ATTACK_DAMAGE_TARGET, "Long-Ranged Damage +%d%%.");
        enc.put(EnchantList.RANGE_ATTACK_DAMAGE_USER, "Long-Ranged Resistance +%d%%.");
        enc.put(EnchantList.HEAL_VALUE, "Skill Healing Recovery Rate +%d%%.");
        enc.put(EnchantList.HEAL_MODIFY_PERCENT, "Received Recovery Rate +%d%%.");
        enc.put(EnchantList.DEC_SPELL_CAST_TIME, "Variable Casting Time -%d%%");
        enc.put(EnchantList.DEC_SPELL_DELAY_TIME, "Cast Delay -%d%%.");
        enc.put(EnchantList.DEC_SP_CONSUMPTION, "Skill SP Cost -%d%%.");
        enc.put(EnchantList.WEAPON_ATTR_NOTHING, "Property: Neutral");
        enc.put(EnchantList.WEAPON_ATTR_WATER, "Property: Water");
        enc.put(EnchantList.WEAPON_ATTR_GROUND, "Property: Earth");
        enc.put(EnchantList.WEAPON_ATTR_FIRE, "Property: Fire");
        enc.put(EnchantList.WEAPON_ATTR_WIND, "Property: Wind");
        enc.put(EnchantList.WEAPON_ATTR_POISON, "Property: Poison");
        enc.put(EnchantList.WEAPON_ATTR_SAINT, "Property: Holy");
        enc.put(EnchantList.WEAPON_ATTR_DARKNESS, "Property: Shadow");
        enc.put(EnchantList.WEAPON_ATTR_TELEKINESIS, "Property: Ghost");
        enc.put(EnchantList.WEAPON_ATTR_UNDEAD, "Property: Undead");

        enchants = enc;
    }

    public static String getEnchant(EnchantList property) {

        if (property == EnchantList.UNKNOWN) {
            return "("+ property +") "+ enchants.get(property);
        } else {
            return enchants.get(property);
        }

    }
}