package com.eclipse.sniffer.enums;

import java.util.Arrays;
import java.util.Optional;

public enum PacketList {
    UNKNOWN("-1"),
    // ACTOR
    ACTOR_EXISTS("09FF"),
    ACTOR_LOOK_AT("009C"),
    ACTOR_INFO_NAME_PREFIX_NAME("0ADF"),
    ACTOR_INFO_NAME_PARTY_GUILD_TITLE("0A30"),
    ACTOR_STATUS_ACTIVE_FLAG("0196"),
    ACTOR_STATUS_ACTIVE_FLAG_TICK_OTHER("043F"),
    ACTOR_STATUS_ACTIVE_FLAG_TOTAL_TICK_OTHER("0983"),
    ACTOR_STATUS_ACTIVE_TOTAL_TICK_OTHER("0984"),
    ACTOR_STATUS_ACTIVE_TICK_OTHER("08FF"),
    ACTOR_MOVE("09FD"),
    ACTOR_MOVE_INTERRUPTED("0088"),
    ACTOR_DIED_OR_DISAPPEARED("0080"),
    ACTOR_CONNECTED("09FE"),
    ACTOR_ACTION("08C8"),
    ACTOR_ACTION_2("008A"),
    ACTOR_ACTION_3("02E1"),
    // CHARACTER
    CHARACTER_STATUS("0229"),
    CHARACTER_MOVES("0087"),
    CHARACTER_NAME("0AF7"),
    CHARACTER_VENDOR_FOUND("0131"),
    CHARACTER_VENDOR_LOST("0132"),
    CHARACTER_OFFLINE_CLONE_FOUND_1("0A89"),
    CHARACTER_OFFLINE_CLONE_FOUND_2("0B05"),
    CHARACTER_OFFLINE_CLONE_LOST("0A8A"),
    CHARACTER_RECEIVED("099D"),
    CHARACTER_RECEIVED_ID_AND_MAP("0071"),
    CHARACTER_INFO_RECEIVED("082D"),
    CHARACTER_SYNC_RECEIVED("09A0"),
    CHARACTER_OVERWEIGHT_PERCENT("0ADE"),
    CHARACTER_SKILL_LIST("010F"),
    // GUILD
    GUILD_MASTER_MEMBER("014E"),
    GUILD_MEMBERS_TITLE_LIST("0166"),
    GUILD_MEMBERS_LIST("0154"),
    GUILD_NOTICE("016F"),
    GUILD_INFO("01B6"),
    GUILD_CHAT("017F"),
    GUILD_MEMBER_ONLINE_STATUS("01F2"),
    GUILD_LOCATION("01EB"),
    GUILD_ALLIES_ENEMY_LIST("014C"),
    GUILD_EMBLEM("0152"),
    GUILD_NAME("016C"),
    GUILD_MEMBER_ADD("0182"),
    // VENDOR
    VENDOR_ITEMS_LIST("0A8D"),
    // BUYING
    BUYING_STORE_LOST("0816"),
    BUYING_STORE_FOUND("0814"),
    // PLAYER
    PLAYER_EQUIPMENT("01D7"),
    // SKILL
    SKILL_CAST("07FB"),
    SKILL_CAST_2("013E"),
    SKILL_USE("01DE"),
    SKILL_USED_LOCATION("0117"),
    SKILL_USED_NO_DAMAGE("011A"),
    SKILL_ADD("0111"),
    SKILL_USE_FAILED("0110"),
    SKILL_POST_DELAY("043D"),
    // PET
    PET_EMOTION("01AA"),
    // ITEM
    ITEM_APPEARED("009E"),
    ITEM_USED("01C8"),
    ITEM_EXISTS("009D"),
    ITEM_DISAPPEARED("00A1"),
    ITEM_LIST_START("0B08"),
    ITEM_LIST_STACKABLE("0B09"),
    ITEM_LIST_NON_STACKABLE("0B0A"),
    ITEM_LIST_END("0B0B"),
    // CHAT
    CHAT_PUBLIC("008D"),
    CHAT_SELF("008E"),
    CHAT_INFO("00D7"),
    CHAT_REMOVED("00D8"),
    // SPELL
    SPELL_AREA("011F"),
    SPELL_AREA_DISAPPEARS("0120"),
    SPELL_AREA_MULTIPLE2("099F"),
    SPELL_AREA_MULTIPLE3("09CA"),
    // PARTY
    PARTY_LOCATION("0107"),
    PARTY_JOIN("0AE4"),
    PARTY_HP_INFO("080E"),
    PARTY_CHAT("0109"),
    PARTY_LV_INFO("0ABD"),
    PARTY_DEAD("0AB2"),
    PARTY_ALLOW_INVITE("02C9"),
    PARTY_USERS_INFO("0AE5"),
    PARTY_EXP("0101"),
    PARTY_LEAVE("0105"),
    // MONSTER
    MONSTER_HP_INFO_TINY("0A36"),
    MONSTER_RANGED_ATTACK("0139"),
    // RODEX
    RODEX_MAIL_LIST("0AC2"),
    RODEX_READ_MAIL("09EB"),
    RODEX_GET_ITEM("09F4"),
    UNREAD_RODEX("09E7"),
    // NPC
    NPC_TALK("00B4"),
    NPC_TALK_CONTINUE("00B5"),
    NPC_TALK_RESPONSE("00B7"),
    NPC_IMAGE("01B3"),
    NPC_TALK_CLOSE("00B6"),
    NPC_STORE_BEGIN("00C4"),
    NPC_STORE_INFO("00C6"),
    NPC_SELL_LIST("00C7"),
    NPC_MARKET_INFO("09D5"),
    // ACCOUNTS
    ACCOUNT_SERVER_INFO("0069"),
    // QUEST
    QUEST_ALL_LIST("09F8"),
    // MAP
    MAP_PROPERTY("01D6"),
    MAP_PROPERTY_3("099B"),
    MAP_LOADED("02EB"),
    MAP_MINI_INDICATOR("0446"),
    MAP_CHANGE("0091"),
    MAP_CHANGED("0092"),
    // ??
    UNEQUIP_ITEM("099A"),
    EQUIP_ITEM("0999"),
    RESURRECTION("0148"),
    INVENTORY_ITEM_REMOVED("07FA"),
    MILLENIUM_SHIELD("0440"),
    DEVOTION("01CF"),
    VENDER_ITEMS_LIST("0800"),
    SEARCH_STORE_OPEN("083A"),
    SEARCH_STORE_RESULT("0836"),
    WARP_PORTAL_LIST("011C"),
    DEAL_BEGIN("01F5"),
    PRIVATE_MESSAGE("09DE"),
    HIGH_JUMP("08D2"),
    HIGH_JUMP_2("01FF"),
    REVOLVING_ENTITY("01D0"),
    LOCAL_BROADCAST("01C3"),
    MESSAGE_STRING("0291"),
    RATES_INFO_2("097B"),
    STATS_INFO("00BD"),
    ACHIEVEMENT_LIST("0A23"),
    FRIEND_LIST("0201"),
    SWITCH_CHARACTER("00B3"),
    CASH_SHOP_LIST("08CA"),
    LOGIN_ERROR("006A"),
    ACHIEVEMENT_UPDATE("0A24"),
    MISC_CONFIG("0ADC"),
    HOTKEYS("07D9"),
    ATTACK_RANGE("013A"),
    ACCOUNT_ID("0283"),
    UNIT_LEVELUP("019B"),
    INVENTORY_ITEM_ADDED("0A37"),
    HET_EFFECT("0A3B"),
    EMOTICON("00C0"),
    HP_SP_CHANGED("0A27"),
    SHOW_EQ("0B03"),
    EXP("0ACC"),
    FRIEND_LOGON("0206"),
    ERRORS("0081"),
    STAT_INFO_1("00B0"),
    STAT_INFO_2("00B1"),
    STAT_INFO_3("0141"),
    STAT_INFO_4("0ACB"),
    MISC_CONFIG_REPLY("02D9"),
    SYNC_REQUEST("0187"),
    RECEIVED_SYNC("007F"),
    EAC_KEY("0A7B"),
    NO_TELEPORT("0189"),
    QUIT_RESPONSE("018B"),
    CAST_CANCELLED("01B9"),
    // EMPTY
    EMPTY_1("0870"),
    EMPTY_2("0838"),
    EMPTY_3("087E"),
    EMPTY_4("087F");

    private final String ident;

    PacketList(String ident) {
        this.ident = ident;
    }

    public static PacketList getValue(String ident) {
        Optional<PacketList> opt =  Arrays.stream(values())
                .filter(PacketList -> PacketList.ident.equals(ident))
                .findFirst();

        return opt.orElse(PacketList.UNKNOWN);
    }

}